### ISSUE TITLE
How does this works???

### ISSUE THREAD

**Issue by shabeebrizvi** [GooGee/Code-Generator#1]
Looks quite interesting but not sure how does it work? Could you please provide some details! Thanks

**Comment by GooGee** [comment]
It's a PHPStorm plugin, https://plugins.jetbrains.com/plugin/15276-laravel-code-generator

**Comment by shabeebrizvi** [comment]
Thanks for your prompt response.... Ya I installed the plugin but not sure how to use it. Also I came across your other project Entity-Builder, it got me all excited wondering how to make these tools to work. I would be more than happy to learn how to use these two. I would appreciate if you can share the steps to setup. I will post my comments on the other project page for what I have tried so far but couldn't make it work. Thanks! and Congrats again for all your efforts!!! 👍👏🙌

**Comment by GooGee** [comment]
I'll make a guide soon. Thanks for your advises.

**Comment by shabeebrizvi** [comment]
Install the Laravel Code Generator plugin from within PhpStorm Marketplace
<img width="2560" alt="Screen Shot 2020-11-13 at 12 58 57 AM" src="https://user-images.githubusercontent.com/16752413/99043519-99521380-254b-11eb-8eb5-0f395e9f046c.png">

Once installed navigate to [View -> Tools Windows -> Code Generator] to activate.
<img width="700" alt="Screen Shot 2020-11-13 at 12 56 05 AM" src="https://user-images.githubusercontent.com/16752413/99043192-36f91300-254b-11eb-97e5-424bb89be083.png">

Hope this would help someone else looking for help!
